begin;
create extension if not exists pgtap with schema extensions;
select plan(22);
select ok(exists(select 1 from public.rbac_permissions where action = 'read' and resource = 'assets'), 'assets read permission exists');
select ok(exists(select 1 from public.rbac_permissions where action = 'create' and resource = 'assets'), 'assets create permission exists');
select ok(exists(select 1 from public.rbac_permissions where action = 'update' and resource = 'assets'), 'assets update permission exists');
select ok(exists(select 1 from public.rbac_permissions where action = 'delete' and resource = 'assets'), 'assets delete permission exists');
select ok(exists(select 1 from public.rbac_permissions where action = 'read' and resource = 'certificates'), 'certificates read permission exists');
select ok(exists(select 1 from public.rbac_permissions where action = 'create' and resource = 'certificates'), 'certificates create permission exists');
select ok(exists(select 1 from public.rbac_permissions where action = 'update' and resource = 'certificates'), 'certificates update permission exists');
select ok(exists(select 1 from public.rbac_permissions where action = 'delete' and resource = 'certificates'), 'certificates delete permission exists');
select policies_are('public', 'assets', array['assets_same_company_read', 'assets_same_company_write', 'assets_same_company_update', 'assets_same_company_delete'], 'asset CRUD policies are present');
select policies_are('public', 'certificates', array['certificates_traceability_read', 'certificates_traceability_write', 'certificates_traceability_update', 'certificates_traceability_delete'], 'certificate CRUD policies are present');
select is((select count(*) from pg_policies where tablename = 'assets' and policyname like 'assets_same_company_%' and (coalesce(qual, '') || coalesce(with_check, '')) like '%trazabilidad%'), 4::bigint, 'all asset policies use trazabilidad');
select is((select count(*) from pg_policies where tablename = 'certificates' and policyname like 'certificates_traceability_%' and (coalesce(qual, '') || coalesce(with_check, '')) like '%trazabilidad%'), 4::bigint, 'all certificate policies use trazabilidad');
select is((select count(*) from pg_policies where tablename in ('assets', 'certificates') and (coalesce(qual, '') || coalesce(with_check, '')) like '%operations%'), 0::bigint, 'policies do not use operations');
select is((select count(*) from pg_policies where tablename in ('assets', 'certificates') and policyname in ('assets_same_company_read', 'assets_same_company_write', 'assets_same_company_update', 'assets_same_company_delete', 'certificates_traceability_read', 'certificates_traceability_write', 'certificates_traceability_update', 'certificates_traceability_delete') and (coalesce(qual, '') || coalesce(with_check, '')) like '%rbac_request_company_id%'), 8::bigint, 'policies isolate by request company');
select ok((select cmd from pg_policies where policyname = 'assets_same_company_read') = 'SELECT', 'asset read action is retained');
select ok((select cmd from pg_policies where policyname = 'assets_same_company_write') = 'INSERT', 'asset create action is retained');
select ok((select cmd from pg_policies where policyname = 'assets_same_company_update') = 'UPDATE', 'asset update action is retained');
select ok((select cmd from pg_policies where policyname = 'assets_same_company_delete') = 'DELETE', 'asset delete action is retained');
select ok((select cmd from pg_policies where policyname = 'certificates_traceability_read') = 'SELECT', 'certificate read action is retained');
select ok((select cmd from pg_policies where policyname = 'certificates_traceability_write') = 'INSERT', 'certificate create action is retained');
select ok((select cmd from pg_policies where policyname = 'certificates_traceability_update') = 'UPDATE', 'certificate update action is retained');
select ok((select cmd from pg_policies where policyname = 'certificates_traceability_delete') = 'DELETE', 'certificate delete action is retained');
select * from finish(); rollback;
