"use client";
import { useState, type FormEvent } from "react";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { Button } from "@/src/core/presentation/components/ui/button";
import { Input } from "@/src/core/presentation/components/ui/input";
import { Label } from "@/src/core/presentation/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/src/core/presentation/components/ui/table";
import { AssetInventoryItem, getInventoryAvailability } from "../../domain/entities";
import { InventoryInput } from "../../application/usecases/inventory.usecases";
import { useInventoryManagement } from "../hooks/use-asset-inventory";

const equipmentTypes = ["Motores de Generadores", "Bombas de Lodo", "Top Drive", "Malacate", "HPU", "Bomba Koomey"];
const blank = (assetId = ""): InventoryInput => ({ assetId, material: "", specification: "", quantityInStock: 0, minimumStock: 0, scope: "asset", equipmentType: "" });

export function InventoryManagementModal({ assets }: { assets: Array<{ id: string; equipment: string }> }) {
  const { items, isLoading, error, save, remove } = useInventoryManagement();
  const [form, setForm] = useState<InventoryInput>(blank(assets[0]?.id));
  const [editing, setEditing] = useState<string>(); const [message, setMessage] = useState<string>();
  const submit = async (event: FormEvent) => { event.preventDefault(); setMessage(undefined); const result = await save(form, editing); if (result.error) setMessage(result.error); else { setMessage("Material guardado correctamente."); setEditing(undefined); setForm(blank(assets[0]?.id)); } };
  const edit = (item: AssetInventoryItem) => { setEditing(item.id); setForm({ ...item }); };
  return <div className="grid max-h-[90vh] min-h-0 gap-6 overflow-y-auto lg:grid-cols-[minmax(280px,0.8fr)_minmax(0,1.4fr)]">
    <section className="space-y-4"><div><h2 className="text-lg font-semibold">{editing ? "Editar material" : "Registrar material"}</h2><p className="text-sm text-muted-foreground">Define explícitamente a qué alcance pertenece el inventario.</p></div>
      <form onSubmit={submit} className="space-y-4 rounded-lg border p-4">
        <fieldset className="space-y-2"><legend className="mb-2 text-sm font-medium">Alcance del inventario</legend><div className="grid grid-cols-2 gap-2"><Button type="button" variant={form.scope === "asset" ? "default" : "outline"} onClick={() => setForm({ ...form, scope: "asset", equipmentType: "" })}>Por activo</Button><Button type="button" variant={form.scope === "shared_equipment_type" ? "default" : "outline"} onClick={() => setForm({ ...form, scope: "shared_equipment_type" })}>Compartido</Button></div></fieldset>
        {form.scope === "asset" ? <div className="space-y-2"><Label htmlFor="inventory-asset">Activo</Label><select id="inventory-asset" required value={form.assetId} onChange={e => setForm({ ...form, assetId: e.target.value })} className="h-9 w-full rounded-md border bg-background px-3 text-sm"><option value="">Selecciona un activo</option>{assets.map(a => <option key={a.id} value={a.id}>{a.equipment}</option>)}</select></div> : <div className="space-y-2"><Label htmlFor="inventory-type">Tipo de equipo</Label><select id="inventory-type" required value={form.equipmentType} onChange={e => setForm({ ...form, equipmentType: e.target.value })} className="h-9 w-full rounded-md border bg-background px-3 text-sm"><option value="">Selecciona un tipo</option>{equipmentTypes.map(type => <option key={type}>{type}</option>)}</select></div>}
        <div className="space-y-2"><Label htmlFor="inventory-material">Material o consumible</Label><Input id="inventory-material" required value={form.material} onChange={e => setForm({ ...form, material: e.target.value })} /></div><div className="space-y-2"><Label htmlFor="inventory-spec">Especificación / número de parte</Label><Input id="inventory-spec" required value={form.specification} onChange={e => setForm({ ...form, specification: e.target.value })} /></div><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label htmlFor="inventory-qty">Existencia</Label><Input id="inventory-qty" type="number" min="0" step="1" required value={form.quantityInStock} onChange={e => setForm({ ...form, quantityInStock: Number(e.target.value) })} /></div><div className="space-y-2"><Label htmlFor="inventory-min">Mínimo</Label><Input id="inventory-min" type="number" min="0" step="1" required value={form.minimumStock} onChange={e => setForm({ ...form, minimumStock: Number(e.target.value) })} /></div></div>
        {message && <p role="status" className="text-sm text-emerald-600">{message}</p>}<div className="flex gap-2"><Button type="submit"><Plus />{editing ? "Actualizar" : "Guardar"}</Button>{editing && <Button type="button" variant="outline" onClick={() => { setEditing(undefined); setForm(blank(assets[0]?.id)); }}>Cancelar</Button>}</div>
      </form>
    </section><section className="min-w-0 space-y-3"><div><h2 className="text-lg font-semibold">Inventario registrado</h2><p className="text-sm text-muted-foreground">Los avisos de stock se calculan por existencia y mínimo.</p></div>{isLoading ? <p role="status">Cargando inventario...</p> : error ? <p role="alert" className="text-sm text-destructive">{error}</p> : items.length === 0 ? <p className="rounded-lg border border-dashed p-8 text-center text-muted-foreground">No hay materiales registrados.</p> : <Table><TableHeader><TableRow><TableHead>Material</TableHead><TableHead>Alcance</TableHead><TableHead>Stock</TableHead><TableHead>Estado</TableHead><TableHead className="text-right">Acciones</TableHead></TableRow></TableHeader><TableBody>{items.map(item => { const status = getInventoryAvailability(item); return <TableRow key={item.id}><TableCell><div className="font-medium">{item.material}</div><div className="text-xs text-muted-foreground">{item.specification}</div></TableCell><TableCell>{item.scope === "asset" ? item.assetId : item.equipmentType}</TableCell><TableCell>{item.quantityInStock} / {item.minimumStock}</TableCell><TableCell><span className={status === "sufficient" ? "text-emerald-600" : "text-orange-600"}>{status === "sufficient" ? "Suficiente" : status === "critical" ? "Crítico" : "Agotado"}</span></TableCell><TableCell className="text-right"><Button aria-label={`Editar ${item.material}`} size="icon-sm" variant="ghost" onClick={() => edit(item)}><Pencil /></Button><Button aria-label={`Eliminar ${item.material}`} size="icon-sm" variant="ghost" onClick={async () => { if (window.confirm("¿Eliminar este material?")) await remove(item.id); }}><Trash2 /></Button></TableCell></TableRow>; })}</TableBody></Table>}</section>
  </div>;
}
