import { OvertimeRecord, TimesheetStats } from "../domain/entities";
import { ITimesheetRepository } from "../domain/repository";

const overtimeRecords: OvertimeRecord[] = [
  {
    id: "OT-001",
    worker: "Luis Martinez",
    workerRole: "Operador de Plataforma",
    platform: "Plataforma Norte",
    date: "2026-02-25",
    hoursRegular: 8,
    hoursOvertime: 4,
    reason: "Mantenimiento de emergencia en bomba BC-12",
    authorizedBy: "Carlos Mendez",
    authorizedDate: "2026-02-25",
    completedDate: "2026-02-25",
    status: "approved",
  },
  {
    id: "OT-002",
    worker: "Ana Rodriguez",
    workerRole: "Ingeniera de Produccion",
    platform: "Plataforma Sur",
    date: "2026-02-25",
    hoursRegular: 8,
    hoursOvertime: 3,
    reason: "Supervision de pruebas de presion en Pozo PF-042",
    authorizedBy: "Carlos Mendez",
    authorizedDate: "2026-02-25",
    completedDate: "2026-02-26",
    status: "approved",
  },
  {
    id: "OT-003",
    worker: "Pedro Gonzalez",
    workerRole: "Tecnico de Instrumentacion",
    platform: "Plataforma Este",
    date: "2026-02-24",
    hoursRegular: 8,
    hoursOvertime: 6,
    reason: "Calibracion de sensores de flujo (programada)",
    authorizedBy: null,
    authorizedDate: null,
    completedDate: null,
    status: "pending",
  },
  {
    id: "OT-004",
    worker: "Maria Fernandez",
    workerRole: "Ingeniera de Seguridad",
    platform: "Plataforma Norte",
    date: "2026-02-24",
    hoursRegular: 8,
    hoursOvertime: 2,
    reason: "Inspeccion de seguridad post-incidente menor",
    authorizedBy: "Jorge Ramirez",
    authorizedDate: "2026-02-24",
    completedDate: "2026-02-24",
    status: "approved",
  },
  {
    id: "OT-005",
    worker: "Roberto Silva",
    workerRole: "Soldador Certificado",
    platform: "Plataforma Sur",
    date: "2026-02-23",
    hoursRegular: 8,
    hoursOvertime: 5,
    reason: "Reparacion de tuberia de alta presion",
    authorizedBy: "Carlos Mendez",
    authorizedDate: "2026-02-23",
    completedDate: "2026-02-23",
    status: "approved",
  },
  {
    id: "OT-006",
    worker: "Diana Lopez",
    workerRole: "Operadora de Consola",
    platform: "Plataforma Norte",
    date: "2026-02-23",
    hoursRegular: 8,
    hoursOvertime: 4,
    reason: "Cobertura de turno por ausencia de personal",
    authorizedBy: null,
    authorizedDate: null,
    completedDate: null,
    status: "pending",
  },
  {
    id: "OT-007",
    worker: "Enrique Morales",
    workerRole: "Electricista Industrial",
    platform: "Plataforma Este",
    date: "2026-02-22",
    hoursRegular: 8,
    hoursOvertime: 3,
    reason: "Revision de tablero electrico principal",
    authorizedBy: "Jorge Ramirez",
    authorizedDate: "2026-02-23",
    completedDate: null,
    status: "rejected",
  },
  {
    id: "OT-008",
    worker: "Carmen Herrera",
    workerRole: "Tecnico de Laboratorio",
    platform: "Plataforma Sur",
    date: "2026-02-22",
    hoursRegular: 8,
    hoursOvertime: 2,
    reason: "Analisis urgente de muestras de crudo",
    authorizedBy: "Carlos Mendez",
    authorizedDate: "2026-02-22",
    completedDate: "2026-02-22",
    status: "approved",
  },
];

export class MockTimesheetRepository implements ITimesheetRepository {
  async getOvertimeRecords(): Promise<OvertimeRecord[]> {
    return overtimeRecords;
  }

  async getWeeklyStats(): Promise<TimesheetStats> {
    return {
      totalOvertime: overtimeRecords.reduce(
        (acc, r) => acc + r.hoursOvertime,
        0,
      ),
      approved: overtimeRecords.filter((r) => r.status === "approved").length,
      pending: overtimeRecords.filter((r) => r.status === "pending").length,
      rejected: overtimeRecords.filter((r) => r.status === "rejected").length,
      totalWorkers: new Set(overtimeRecords.map((r) => r.worker)).size,
    };
  }
}
