-- Seed tool assets from HERRAMIETA (44 records).
do $$
declare v_company_id uuid := null; v_location_id uuid; v_ubication_id uuid; v_principle_id uuid; v_row_no integer := 1; v_asset record; begin
  if v_company_id is null then raise exception 'Set v_company_id before executing this snippet'; end if;
  for v_asset in select * from (values
    ('RIG 703', 'CHANGERA', 'MADRINA DE CARGA', null::text, null::text, 'HDH-104095', null::text, null::text, null::text, null::text, null::text, null::text, 'DS 55', '6 5/8', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, '0.96', null::text, null::text, null::text, null::text),
    ('RIG 703', 'CHANGERA', 'MADRINA DE CARGA', null::text, null::text, 'HDH-104186', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, '0.97', null::text, null::text, null::text, null::text),
    ('RIG 703', 'CHANGERA', 'MADRINA DE CARGA', null::text, null::text, 'HDH-104143', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, '0.99', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PISO', 'MADRINA DE CARGA', null::text, null::text, 'HDH-104184', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, 'B', null::text, null::text, null::text, null::text, null::text, '0.99', null::text, null::text, null::text, null::text),
    ('RIG 703', 'CHANGERA', 'MADRINA DE CARGA', null::text, null::text, 'HDH-104138', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, '1.01', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'MADRINA DE CARGA', null::text, null::text, 'HDH-104137', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, '1.02', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'MADRINA DE CARGA', null::text, null::text, 'HDH-104139', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, '0.97', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'MADRINA DE CARGA', null::text, null::text, 'Ixachi-HDH-104164', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, 'B', null::text, null::text, null::text, null::text, null::text, '0.88', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PISO', 'MADRINA DE CARGA', null::text, null::text, '14031459', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'DOBLE CAJA', null::text, null::text, 'HDH-104174', null::text, null::text, null::text, null::text, null::text, null::text, '7 5/8 reg.', '7 5/8', '9  1/2"', '3  1/8"', null::text, null::text, null::text, null::text, null::text, null::text, '1.21', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'DOBLE CAJA', null::text, null::text, 'HDH-104265', null::text, null::text, null::text, null::text, null::text, null::text, '7 5/8 reg.', '7 5/8 reg.', '9  5/8"', '4  3/4"', null::text, null::text, null::text, null::text, null::text, null::text, '1.07', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'DOBLE PIN', null::text, null::text, 'PBM820', null::text, null::text, null::text, null::text, null::text, null::text, '7 5/8 pin', 'DS 55 pin', '8  7/8"', '3"', null::text, null::text, null::text, null::text, null::text, null::text, '0.36', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'DOBLE PIN', null::text, null::text, 'IXACHI-1223-04', null::text, null::text, null::text, null::text, null::text, null::text, '7 5/8 pin', 'DS 55 pin', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, '0.32', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'DOBLE PIN', null::text, null::text, 'Perf-207-11-T37', null::text, null::text, null::text, null::text, null::text, null::text, '7 5/8', 'DS 55', '8  7/8"', '2 13/16"', 'B', null::text, null::text, null::text, null::text, null::text, '0.36', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'DOBLE PIN', null::text, null::text, 'Perf-207-10-T37', null::text, null::text, null::text, null::text, null::text, null::text, '7 5/8"', 'DS 55', '8  7/8"', '2  13/16"', 'B', null::text, null::text, null::text, null::text, null::text, '0.36', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'DOBLE PIN', null::text, null::text, 'Ixachi-1223-04', null::text, null::text, null::text, null::text, null::text, null::text, '7 5/8"', 'DS 55', '8  7/8"', '3"', 'M', null::text, null::text, null::text, null::text, null::text, '0.57999999999999996', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PISO', 'COMBINACION', null::text, null::text, 'MDS-084.25-01', null::text, null::text, null::text, null::text, null::text, null::text, '6 5/8 reg', '7 5/8', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, '0.88', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PISO', 'COMBINACION', null::text, null::text, 'HDH-104119', null::text, null::text, null::text, null::text, null::text, null::text, 'DS 55', '7 5/8', '7" x 9 1/4"', '3"', 'B', null::text, null::text, null::text, null::text, null::text, '0.85', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PISO', 'COMBINACION', null::text, null::text, 'KOSVAC-2026-001', null::text, null::text, null::text, null::text, null::text, null::text, '6 5/8 reg', '7 5/8', '7 7/8" x 9 3/8"', '2 7/8"', 'B', null::text, null::text, null::text, null::text, null::text, '0.86', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PISO', 'COMBINACION', null::text, null::text, 'Rig703-PGB809', null::text, null::text, null::text, null::text, null::text, null::text, 'DS 55', '6 5/8', '8"', '2  3/4"', 'B', null::text, null::text, null::text, null::text, null::text, '1.0900000000000001', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PISO', 'COMBINACION', null::text, null::text, 'Combinacion prueba de BOP´s', null::text, null::text, null::text, null::text, null::text, null::text, 'DS 55', 'NC 50', null::text, null::text, 'B', null::text, null::text, null::text, null::text, null::text, '0.3', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PISO', 'COMBINACION', null::text, null::text, 'Perfio-199-04-T37', null::text, null::text, null::text, null::text, null::text, null::text, '6 5/8', '7 5/8', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, '1.08', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PISO', 'COMBINACION', null::text, null::text, 'Perfio-207-12-T37', null::text, null::text, null::text, null::text, null::text, null::text, 'DS 55', '6 5/8', '7 1/16" x 8 3/8"', '2  7/8"', 'B', null::text, null::text, null::text, null::text, null::text, '1.1000000000000001', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'COMBINACION', null::text, null::text, 'Rig703/PGB814', null::text, null::text, null::text, null::text, null::text, null::text, 'NC46', 'NC 50', '6 1/2"', '2 7/8"', 'B', null::text, null::text, null::text, null::text, null::text, '1.08', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'COMBINACION', null::text, null::text, 'HDH104314', null::text, null::text, null::text, null::text, null::text, null::text, 'DS 55', 'NC46', '7" x 6 1/2"', '3"', null::text, null::text, null::text, null::text, null::text, null::text, '1', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PISO', 'COMBINACION', null::text, null::text, 'MQS320/23-01', null::text, null::text, null::text, null::text, null::text, null::text, 'NC46', 'NC50', '6 3/4"', '3"', 'B', null::text, null::text, null::text, null::text, null::text, '1.07', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'COMBINACION', null::text, null::text, 'MQS063/25-02', null::text, null::text, null::text, null::text, null::text, null::text, 'DS 55', '6 5/8', '8 1/4" x 7"', '2 7/8"', 'B', null::text, null::text, null::text, null::text, null::text, '1.02', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'COMBINACION', null::text, null::text, 'Rig703PGB810', null::text, null::text, null::text, null::text, null::text, null::text, 'DS 55', '6 5/8', '8"', '2 7/8"', 'B', null::text, null::text, null::text, null::text, null::text, '0.98', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'COMBINACION', null::text, null::text, 'HDH-104164', null::text, null::text, null::text, null::text, null::text, null::text, 'DS 55', '7 5/8', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, '0.87', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'COMBINACION', null::text, null::text, 'MQS-063/25-01', null::text, null::text, null::text, null::text, null::text, null::text, 'DS 55', '6 5/8', '8 1/8" x 7"', '2 7/8"', 'B', null::text, null::text, null::text, null::text, null::text, '0.83', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'COMBINACION', null::text, null::text, 'HDH104120', null::text, null::text, null::text, null::text, null::text, null::text, 'DS 55', '7 5/8 reg.', '9 1/4" x 7"', '3"', 'B', null::text, null::text, null::text, null::text, null::text, '1', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PISO', 'COMBINACION', null::text, null::text, 'Perfio-192-04-T37', null::text, null::text, null::text, null::text, null::text, null::text, '7 5/8"', '6 5/8"', null::text, null::text, 'B', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text),
    ('RIG 703', 'PISO', 'COMBINACION', null::text, null::text, 'S/N', null::text, null::text, null::text, null::text, null::text, null::text, '6 5/8"', '7 5/8"', null::text, null::text, 'B', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'VALVULA CONTRA PRESION', null::text, null::text, 'M8M76230', null::text, null::text, null::text, null::text, null::text, null::text, 'DS 55', 'DS55 5 1/2', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, '0.59', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'VALVULA IBOP TOP DRIVE', null::text, null::text, '1029-03620-91', null::text, null::text, null::text, null::text, null::text, null::text, '7 5/8', '7 5/8', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, '0.87', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'VALVULA MANUAL TOP DRIVE', null::text, null::text, 'M8M85366', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, '0.41', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'VALVULA INSIDE BOP', null::text, null::text, 'DM16390H25', null::text, null::text, null::text, null::text, null::text, null::text, 'DS 55', 'DS 55 ', '7 1/4"', '2 1/4"', null::text, null::text, null::text, null::text, null::text, null::text, '0.9', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'VALVULA INSIDE BOP', null::text, null::text, 'DM-702-012', null::text, null::text, null::text, null::text, null::text, null::text, 'DS 55', 'DS 55', '7 1/4"', '2 1/4"', null::text, null::text, null::text, null::text, null::text, null::text, '0.91', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'SIDE ENTRY CON LATERAL 1502', null::text, null::text, 'MQS-061/25-01', null::text, null::text, null::text, null::text, null::text, null::text, 'DS 55', 'DS 55', '7 5/8"', '3 3/4"', null::text, null::text, null::text, null::text, null::text, null::text, '0.36', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'VALVULA MANUAL TOP DRIVE', null::text, null::text, '11-06-26-01', null::text, null::text, null::text, null::text, null::text, null::text, '7 5/8', '7 5/8', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text),
    ('RIG 703', 'PISO', 'VALVULA DE PIE', null::text, null::text, 'M8M76290', null::text, null::text, null::text, null::text, null::text, null::text, '6 5/8"', 'DS 55', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, '0.59', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'LINE OUTLET', null::text, null::text, 'MQS061/25-01', null::text, null::text, null::text, null::text, null::text, null::text, 'DS 55', 'DS 55x1502', '7"', '2 7/8"', null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'BOTELLA DE CIRCULACION', null::text, null::text, 'IXA-703-1003', null::text, null::text, null::text, null::text, null::text, null::text, '1502', 'XT57', '7 1/16"', '2 1/8"', null::text, null::text, null::text, null::text, null::text, null::text, '0.32', null::text, null::text, null::text, null::text),
    ('RIG 703', 'PATIO', 'BOTELLA DE CIRCULACION', null::text, null::text, 'Perfo-200-07-T37GPDS-55', null::text, null::text, null::text, null::text, null::text, null::text, '1502', 'DS 55', '7 1/4"', '1 1/8"', null::text, null::text, null::text, null::text, null::text, null::text, '0.64', null::text, null::text, null::text, null::text)) as x(location_name,ubication_name,principle_name,brand_name,model_name,serial_number,inspection_code,property_1,property_2,property_3,property_4,property_5,property_6,property_7,property_8,property_9,property_10,property_11,property_12,property_13,property_14,property_15,property_16,property_17,property_18,property_19,property_20) loop
    select id into v_location_id from public.locations where company_id=v_company_id and name=v_asset.location_name limit 1;
    if v_location_id is null then raise exception 'Row %, serial %: location % was not found for company %',v_row_no,v_asset.serial_number,v_asset.location_name,v_company_id; end if;
    select id into v_ubication_id from public.ubications where company_id=v_company_id and name=v_asset.ubication_name limit 1;
    if v_ubication_id is null then raise exception 'Row %, serial %: ubication % was not found for company %',v_row_no,v_asset.serial_number,v_asset.ubication_name,v_company_id; end if;
    select id into v_principle_id from public.functional_principles where company_id=v_company_id and name=v_asset.principle_name and scope_id=(select id from public.functional_principle_scopes where company_id=v_company_id and code='tubular' limit 1) limit 1;
    if v_principle_id is null then raise exception 'Row %, serial %: principle % was not found for company %',v_row_no,v_asset.serial_number,v_asset.principle_name,v_company_id; end if;
     update public.assets set current_location_id=v_location_id,current_ubication_id=v_ubication_id,function_principle_id=v_principle_id,last_inspection_code=v_asset.inspection_code,status='active',is_active=true,property_1=v_asset.property_1,property_2=v_asset.property_2,property_3=v_asset.property_3,property_4=v_asset.property_4,property_5=v_asset.property_5,property_6=v_asset.property_6,property_7=v_asset.property_7,property_8=v_asset.property_8,property_9=v_asset.property_9,property_10=v_asset.property_10,property_11=null::integer,property_12=nullif(v_asset.property_12,'')::integer,property_13=nullif(v_asset.property_13,'')::integer,property_14=nullif(v_asset.property_14,'')::integer,property_15=nullif(v_asset.property_15,'')::integer,property_16=nullif(v_asset.property_16,'')::double precision,property_17=nullif(v_asset.property_17,'')::double precision,property_18=coalesce(nullif(v_asset.property_18,''),nullif(v_asset.property_11,''))::double precision,property_19=nullif(v_asset.property_19,'')::double precision,property_20=nullif(v_asset.property_20,'')::double precision where company_id=v_company_id and serial_number=v_asset.serial_number;
    if not found then
     insert into public.assets(company_id,current_location_id,current_ubication_id,function_principle_id,brand_id,model_id,serial_number,last_inspection_code,status,is_active,property_1,property_2,property_3,property_4,property_5,property_6,property_7,property_8,property_9,property_10,property_11,property_12,property_13,property_14,property_15,property_16,property_17,property_18,property_19,property_20) values(v_company_id,v_location_id,v_ubication_id,v_principle_id,null,null,v_asset.serial_number,v_asset.inspection_code,'active',true,v_asset.property_1,v_asset.property_2,v_asset.property_3,v_asset.property_4,v_asset.property_5,v_asset.property_6,v_asset.property_7,v_asset.property_8,v_asset.property_9,v_asset.property_10,null::integer,nullif(v_asset.property_12,'')::integer,nullif(v_asset.property_13,'')::integer,nullif(v_asset.property_14,'')::integer,nullif(v_asset.property_15,'')::integer,nullif(v_asset.property_16,'')::double precision,nullif(v_asset.property_17,'')::double precision,coalesce(nullif(v_asset.property_18,''),nullif(v_asset.property_11,''))::double precision,nullif(v_asset.property_19,'')::double precision,nullif(v_asset.property_20,'')::double precision);
    end if;
    v_row_no := v_row_no + 1;
  end loop;
end $$;
