"use client";

import { useEffect, useState } from "react";
import { Button } from "@/src/core/presentation/components/ui/button";
import { Input } from "@/src/core/presentation/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/src/core/presentation/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/src/core/presentation/components/ui/table";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/src/core/presentation/components/ui/dialog";
import { useAccessControlAssignments, useAccessControlCompanies, useAccessControlError, useAccessControlLoading, useAccessControlMemberships, useAccessControlPermissions, useAccessControlRolePermissions, useAccessControlRoles, useAccessControlUsers, useExecuteAccessControl, useRefreshAccessControl } from "@/src/features/access-control/presentation/access-control-store";

/** Simple catalog-style administration for the six RBAC MVP resources. */
export function AccessControlPanel() {
  const companies = useAccessControlCompanies(); const users = useAccessControlUsers(); const roles = useAccessControlRoles(); const memberships = useAccessControlMemberships(); const assignments = useAccessControlAssignments(); const permissions = useAccessControlPermissions(); const rolePermissions = useAccessControlRolePermissions();
  const loading = useAccessControlLoading(); const error = useAccessControlError(); const refresh = useRefreshAccessControl(); const execute = useExecuteAccessControl();
  const [name, setName] = useState(""); const [companyId, setCompanyId] = useState(""); const [userId, setUserId] = useState(""); const [roleId, setRoleId] = useState(""); const [permissionId, setPermissionId] = useState("");
  const [editDialog, setEditDialog] = useState<{ id: string; name: string; companyId: string } | null>(null);
  const [editName, setEditName] = useState("");
  useEffect(() => { void refresh(); }, [refresh]);
  const run = (command: Parameters<typeof execute>[0]) => execute(command);
  const openEditDialog = (edit: NonNullable<typeof editDialog>) => { setEditDialog(edit); setEditName(edit.name); };
  const submitEdit = async () => {
    const next = editName.trim();
    if (!editDialog || !next) return;
    const succeeded = await run({ type: "update-role", companyId: editDialog.companyId, roleId: editDialog.id, role: { name: next } });
    if (succeeded) setEditDialog(null);
  };
  return <div className="space-y-4">{error && <p role="alert" className="rounded border border-destructive p-3 text-sm text-destructive">{error}</p>}
    <fieldset disabled={loading} aria-busy={loading}><Tabs defaultValue="companies"><TabsList className="flex-wrap"><TabsTrigger value="companies">Compañías</TabsTrigger><TabsTrigger value="users">Usuarios</TabsTrigger><TabsTrigger value="memberships">Membresías</TabsTrigger><TabsTrigger value="roles">Roles</TabsTrigger><TabsTrigger value="permissions">Permisos por rol</TabsTrigger><TabsTrigger value="assignments">Asignaciones</TabsTrigger></TabsList>
      <TabsContent value="companies"><SimpleTable headers={["Nombre", "Estado"]} rows={companies.map(c => [c.name, c.isActive ? "Activo" : "Inactivo"])} /></TabsContent>
      <TabsContent value="users"><SimpleTable headers={["Correo", "Estado"]} rows={users.map(u => [u.email ?? "Sin correo", u.isActive ? "Activo" : "Inactivo"])} /></TabsContent>
      <TabsContent value="memberships"><Selector companyId={companyId} setCompanyId={setCompanyId} userId={userId} setUserId={setUserId} companies={companies} users={users} /><Button onClick={() => companyId && userId && void run({ type: "set-membership", membership: { companyId, userId, isActive: true } })}>Agregar / activar</Button><SimpleTable headers={["Compañía", "Usuario", "Estado", "Acción"]} rows={memberships.map(m => [companies.find(c => c.id === m.companyId)?.name ?? m.companyId, users.find(u => u.id === m.userId)?.email ?? m.userId, m.isActive ? "Activo" : "Inactivo", <span key="actions" className="flex gap-2"><Button size="sm" variant="outline" onClick={() => void run({ type: "set-membership", membership: { ...m, isActive: !m.isActive } })}>{m.isActive ? "Desactivar" : "Activar"}</Button><Button size="sm" variant="destructive" onClick={() => void run({ type: "remove-membership", membership: m })}>Quitar</Button></span>])} /></TabsContent>
      <TabsContent value="roles"><Selector companyId={companyId} setCompanyId={setCompanyId} companies={companies} /><Editor placeholder="Nombre del rol" value={name} setValue={setName} onAdd={() => companyId && name.trim() && void run({ type: "create-role", companyId, role: { name } })} /><SimpleTable headers={["Nombre", "Compañía", "Acción"]} rows={roles.map(r => [r.name, companies.find(c => c.id === r.companyId)?.name ?? r.companyId ?? "-", <span key="actions" className="flex gap-2"><Button size="sm" variant="outline" onClick={() => r.companyId && openEditDialog({ id: r.id, name: r.name, companyId: r.companyId })}>Editar</Button><Button size="sm" variant="destructive" onClick={() => r.companyId && void run({ type: "delete-role", companyId: r.companyId, roleId: r.id })}>Eliminar</Button></span>])} /></TabsContent>
      <TabsContent value="permissions"><Selector companyId={companyId} setCompanyId={setCompanyId} roleId={roleId} setRoleId={setRoleId} permissionId={permissionId} setPermissionId={setPermissionId} companies={companies} roles={roles} permissions={permissions} /><Button onClick={() => companyId && roleId && permissionId && void run({ type: "set-permission", companyId, roleId, permissionId, enabled: !rolePermissions.some(p => p.roleId === roleId && p.permissionId === permissionId) })}>Alternar permiso</Button><SimpleTable headers={["Rol", "Acción", "Recurso"]} rows={rolePermissions.map(rp => { const p = permissions.find(x => x.id === rp.permissionId); return [roles.find(r => r.id === rp.roleId)?.name ?? rp.roleId, p?.action ?? "-", p?.resource ?? "-"]; })} /></TabsContent>
      <TabsContent value="assignments"><Selector companyId={companyId} setCompanyId={setCompanyId} userId={userId} setUserId={setUserId} roleId={roleId} setRoleId={setRoleId} companies={companies} users={users} roles={roles} /><Button onClick={() => companyId && userId && roleId && void run({ type: "set-assignment", assignment: { companyId, userId, roleId } })}>Asignar rol</Button><SimpleTable headers={["Compañía", "Usuario", "Rol", "Acción"]} rows={assignments.map(a => [companies.find(c => c.id === a.companyId)?.name ?? a.companyId, users.find(u => u.id === a.userId)?.email ?? a.userId, roles.find(r => r.id === a.roleId)?.name ?? a.roleId, <Button key="remove" size="sm" variant="destructive" onClick={() => void run({ type: "remove-assignment", assignment: a })}>Quitar</Button>])} /></TabsContent>
    </Tabs></fieldset>{loading && <p className="text-sm text-muted-foreground">Procesando...</p>}<Dialog open={editDialog !== null} onOpenChange={open => !open && !loading && setEditDialog(null)}><DialogContent><DialogHeader><DialogTitle>Editar rol</DialogTitle><DialogDescription>Actualiza el nombre del registro seleccionado.</DialogDescription></DialogHeader><Input aria-label="Nombre" value={editName} onChange={event => setEditName(event.target.value)} disabled={loading} autoFocus /><DialogFooter><Button variant="outline" onClick={() => setEditDialog(null)} disabled={loading}>Cancelar</Button><Button onClick={() => void submitEdit()} disabled={loading || !editName.trim()}>{loading ? "Guardando..." : "Guardar"}</Button></DialogFooter></DialogContent></Dialog></div>;
}
type Options = { companies?: { id: string; name: string }[]; users?: { id: string; email: string | null }[]; roles?: { id: string; name: string }[]; permissions?: { id: string; action: string; resource: string }[]; companyId?: string; setCompanyId?: (v: string) => void; userId?: string; setUserId?: (v: string) => void; roleId?: string; setRoleId?: (v: string) => void; permissionId?: string; setPermissionId?: (v: string) => void };
function Selector({ companies = [], users = [], roles = [], permissions = [], ...o }: Options) { const fields: { label: string; value?: string; setter?: (v: string) => void; items: { id: string; name?: string; email?: string | null; action?: string; resource?: string }[] }[] = [["Compañía", o.companyId, o.setCompanyId, companies], ["Usuario", o.userId, o.setUserId, users], ["Rol", o.roleId, o.setRoleId, roles], ["Permiso", o.permissionId, o.setPermissionId, permissions]].map(([label, value, setter, items]) => ({ label: label as string, value: value as string | undefined, setter: setter as ((v: string) => void) | undefined, items: items as { id: string; name?: string; email?: string | null; action?: string; resource?: string }[] })); return <div className="mb-3 flex flex-wrap gap-2">{fields.map(field => field.setter && <select key={field.label} className="h-9 rounded-md border bg-background px-2 text-sm" value={field.value ?? ""} onChange={e => field.setter?.(e.target.value)}><option value="">{field.label}</option>{field.items.map(x => <option key={x.id} value={x.id}>{x.name ?? x.email ?? `${x.action} / ${x.resource}`}</option>)}</select>)}</div>; }
function Editor({ placeholder, value, setValue, onAdd }: { placeholder: string; value: string; setValue: (v: string) => void; onAdd: () => void }) { return <div className="mb-3 flex gap-2"><Input className="max-w-sm" placeholder={placeholder} value={value} onChange={e => setValue(e.target.value)} /><Button onClick={onAdd}>Agregar</Button></div>; }
function SimpleTable({ headers, rows }: { headers: string[]; rows: React.ReactNode[][] }) { return <div className="overflow-x-auto rounded-md border"><Table><TableHeader><TableRow>{headers.map(h => <TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.length ? rows.map((row, i) => <TableRow key={i}>{row.map((cell, j) => <TableCell key={j}>{cell}</TableCell>)}</TableRow>) : <TableRow><TableCell colSpan={headers.length} className="py-8 text-center text-muted-foreground">No hay registros.</TableCell></TableRow>}</TableBody></Table></div>; }
